# Generated by Django 3.2.9 on 2021-11-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('width', models.IntegerField(blank=True, default=0, null=True)),
                ('height', models.IntegerField(blank=True, default=0, null=True)),
                ('parent_picture', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
